# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: quickshell
  version: 0.2.0
  binarypath: /usr/bin/quickshell
  distrorepo:
    - distro: nitrux
      release: duke
      arch: amd64
      components:
        - main
    - distro: debian
      release: unstable
      arch: amd64
      components:
        - main
  deps:
    - gnome-themes-extra-data
    - libabsl20240722
    - libasound2-data
    - libasound2t64
    - libasyncns0
    - libb2-1
    - libconfig++11
    - libdouble-conversion3
    - libduktape207
    - libebur128-1
    - libffado2
    - libfftw3-single3
    - libglibmm-2.4-1t64
    - libgomp1
    - libgudev-1.0-0
    - libicu76
    - libiec61883-0
    - libimobiledevice-1.0-6
    - libimobiledevice-glue-1.0-0
    - libinput-bin
    - libinput10
    - libjemalloc2
    - libkf6colorscheme6
    - libkf6configcore6
    - libkf6iconthemes6
    - libkf6qqc2desktopstyle-data
    - libkf6qqc2desktopstyle-dev
    - libkirigamiplatform6
    - liblilv-0-0
    - libmd4c0
    - libmtdev1t64
    - libmysofa1
    - libopenfec1
    - libpam0g
    - libpcre2-16-0
    - libpipewire-0.3-0t64
    - libpipewire-0.3-modules
    - libplist-2.0-4
    - libpolkit-gobject-1-0
    - libproxy1v5
    - libpulse0
    - libqt6core5compat6
    - libqt6core6t64
    - libqt6dbus6
    - libqt6gui6
    - libqt6multimedia6
    - libqt6network6
    - libqt6opengl6
    - libqt6positioning6
    - libqt6printsupport6
    - libqt6qml6
    - libqt6qmlmeta6
    - libqt6qmlmodels6
    - libqt6qmlworkerscript6
    - libqt6quick6
    - libqt6quickcontrols2-6
    - libqt6quickshapes6
    - libqt6quicktemplates2-6
    - libqt6quickwidgets6
    - libqt6sql6
    - libqt6sql6-sqlite
    - libqt6svg6
    - libqt6texttospeech6
    - libqt6waylandclient6
    - libqt6waylandcompositor6
    - libqt6widgets6
    - libqt6wlshellintegration6
    - libqt6xml6
    - libraw1394-11
    - libroc0.4
    - libserd-0-0
    - libsigc++-2.0-0v5
    - libsndfile1
    - libsord-0-0
    - libspa-0.2-modules
    - libspeexdsp1
    - libsratom-0-0
    - libts0t64
    - libupower-glib3
    - libusbmuxd-2.0-7
    - libuv1t64
    - libvorbis0a
    - libvorbisenc2
    - libwacom-common
    - libwacom9
    - libwebrtc-audio-processing-1-3
    - libxcb-cursor0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-render-util0
    - libxcb-shape0
    - libxcb-util1
    - libxcb-xinput0
    - libxcb-xkb1
    - libxcb1
    - libxkbcommon-x11-0
    - libxkbcommon0
    - libxkbfile1
    - libxml++2.6-2v5
    - libzix-0-0
    - pipewire-bin
    - qml6-module-org-kde-desktop
    - qml6-module-qt-labs-folderlistmodel
    - qml6-module-qtcore
    - qml6-module-qtqml
    - qml6-module-qtqml-workerscript
    - qml6-module-qtquick-controls
    - qml6-module-qtquick-effects
    - qml6-module-qtquick-layouts
    - qml6-module-qtquick-shapes
    - qml6-module-qtquick-templates
    - qml6-module-qtquick-tooling
    - qml6-module-qtquick-window
    - qt6-gtk-platformtheme
    - qt6-qpa-plugins
    - qt6-svg-plugins
    - qt6-translations-l10n
    - qt6-wayland
    - quickshell
    - xkb-data
  runtime: uruntime

apprunconf:
  exec: /usr/bin/quickshell
  setpath: /usr/bin
  setlibpath: /usr/lib
  envvars:
    QT_QPA_PLATFORM: "wayland;xcb"
    QT_PLUGIN_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/plugins:$APPDIR/usr/lib/x86_64-linux-gnu/qt6/plugins"
    QT_QML_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/qml:$APPDIR/usr/lib/x86_64-linux-gnu/qt6/qml"
    QML_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt6/qml"
    QML2_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/qml"
    SESSION_MANAGER: ""
    XKB_CONFIG_ROOT: "$APPDIR/usr/share/X11/xkb"
  prebuild_commands: []

sandbox:
  type: bwrap
  dev: true
  proc: true
  tmpfs: true
  unshare-user: true
  unshare-uts: true
  cap-drop-all: true
  die-with-parent: true
  bind:
    - "$HOME:$HOME"
    - ~/.config:~/.config
    - ~/.local:~/.local
    - "$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR"
    - /dev/shm:/dev/shm
  ro-bind:
    - "$APPDIR:$APPDIR"
    - /lib:/lib
    - /lib64:/lib64
    - /usr:/usr
    - /etc/fonts:/etc/fonts
    - /etc/xdg:/etc/xdg
  bwrap_env:
    - HOME: "$HOME"
    - LANG: "en_US.UTF-8"
    - XDG_RUNTIME_DIR: "$XDG_RUNTIME_DIR"
    - WAYLAND_DISPLAY: "$WAYLAND_DISPLAY"
  bwrap_unset-env:
    - DISPLAY

integration:
  type: gui
