# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: vvave
  version: 4.0.0+p22.04+vstable+git20241108.0240-0
  binarypath: /usr/bin/vvave
  distrorepo:
    - distro: ubuntu
      release: jammy
      arch: amd64
      components:
          - main
          - universe
    - distro: kde-neon
      release: jammy
      arch: amd64
  deps:
    - vvave
    - kf6-breeze-icon-theme
    - kf6-kauth
    - kf6-kbookmarks
    - kf6-kcodecs
    - kf6-kcolorscheme
    - kf6-kcompletion
    - kf6-kconfig
    - kf6-kconfigwidgets
    - kf6-kcoreaddons
    - kf6-kcrash
    - kf6-kdbusaddons
    - kf6-kdoctools
    - kf6-kfilemetadata
    - kf6-kguiaddons
    - kf6-ki18n
    - kf6-kiconthemes
    - kf6-kio
    - kf6-kirigami
    - kf6-kitemviews
    - kf6-kjobwidgets
    - kf6-knotifications
    - kf6-kpty
    - kf6-kservice
    - kf6-kstatusnotifieritem
    - kf6-kwallet
    - kf6-kwidgetsaddons
    - kf6-kwindowsystem
    - kf6-solid
    - libaom3
    - libappimage1.0
    - libarchive13
    - libasound2
    - libassimp5
    - libassuan0
    - libasyncns0
    - libavcodec-extra58
    - libavcodec58
    - libavformat58
    - libavutil56
    - libb2-1
    - libbluray2
    - libboost-filesystem1.74.0
    - libcanberra0
    - libchromaprint1
    - libcodec2-1.0
    - libdav1d5
    - libdouble-conversion3
    - libdraco4
    - libduktape207
    - libdw1
    - libepub0
    - libevdev2
    - libexiv2-27
    - libfbclient2
    - libflac8
    - libgif7
    - libgme0
    - libgomp1
    - libgpgme11
    - libgpgmepp6
    - libgsm1
    - libgstreamer-gl1.0-0
    - libgstreamer-plugins-base1.0-0
    - libgstreamer-plugins-good1.0-0
    - libgstreamer1.0-0
    - libgudev-1.0-0
    - libice6
    - libicu70
    - libimobiledevice6
    - libinput10
    - libjpeg-turbo8
    - libldap-2.5-0
    - liblept5
    - libltdl7
    - liblzo2-2
    - libmauikit
    - libmauikitaccounts4
    - libmauikitfilebrowsing4
    - libmauikitimagetools4
    - libmauikitterminal4
    - libmauiman
    - libmd4c0
    - libmfx1
    - libminizip1
    - libmp3lame0
    - libmpg123-0
    - libmtdev1
    - libmysqlclient21
    - libnorm1
    - libnspr4
    - libnss3
    - libnuma1
    - libodbc2
    - libogg0
    - libopenjp2-7
    - libopenmpt0
    - libopus0
    - liborc-0.4-0
    - libpcre2-16-0
    - libpgm-5.3-0
    - libplist3
    - libpolkit-agent-1-0
    - libpolkit-gobject-1-0
    - libpolkit-qt6-1-1
    - libpoppler-qt6-3
    - libpoppler134
    - libpq5
    - libproxy1v5
    - libpulse0
    - libqca-qt6-2
    - libqmobipocket6-2
    - librabbitmq4
    - libshine3
    - libsm6
    - libsnappy1v5
    - libsndfile1
    - libsodium23
    - libsoxr0
    - libspeex1
    - libsquashfuse0
    - libsrt1.4-gnutls
    - libssh-gcrypt-4
    - libswresample3
    - libswscale5
    - libtag1v5-vanilla
    - libtdb1
    - libtesseract4
    - libtheora0
    - libtiff5
    - libtommath1
    - libts0
    - libtwolame0
    - libudfread0
    - libunwind8
    - libusbmuxd6
    - libva-drm2
    - libva-x11-2
    - libva2
    - libvdpau1
    - libvorbis0a
    - libvorbisenc2
    - libvorbisfile3
    - libvpx7
    - libwacom9
    - libwebpmux3
    - libx264-163
    - libx265-199
    - libxcb-cursor0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-render-util0
    - libxcb-res0
    - libxcb-shape0
    - libxcb-util1
    - libxcb-xinput0
    - libxcb-xkb1
    - libxkbcommon-x11-0
    - libxkbcommon0
    - libxslt1.1
    - libxvidcore4
    - libzip4
    - libzmq5
    - libzvbi0
    - mauiman
    - ocl-icd-libopencl1
    - qml6-module-org-maui-mauikit
    - qml6-module-org-mauikit-accounts
    - qml6-module-org-mauikit-filebrowsing
    - qml6-module-org-mauikit-imagetools
    - qml6-module-org-mauikit-terminal
    - qt6-5compat
    - qt6-base
    - qt6-declarative
    - qt6-gtk-platformtheme
    - qt6-multimedia
    - qt6-quick3d
    - qt6-quicktimeline
    - qt6-shadertools
    - qt6-svg
    - qt6-wayland
    - xkb-data
  runtime: go

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/vvave"
  envvars:
    QT_QUICK_CONTROLS_STYLE: "org.mauikit.style"
    QT_QPA_PLATFORM: "xcb"
    QT_PLUGIN_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/plugins:$APPDIR/usr/lib/x86_64-linux-gnu/qt6/plugins"
    QT_QML_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/qml:$APPDIR/usr/lib/x86_64-linux-gnu/qt6/qml"
    QML_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt6/qml"
    QML2_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/qml"
    SESSION_MANAGER: ""
    XKB_CONFIG_ROOT: "$APPDIR/usr/share/X11/xkb"
  prebuild_commands:
    - "rm -f $APPDIR/usr/share/metainfo/org.kde.vvave.appdata.xml"

sandbox:
  type: none

integration:
  type: gui
