#!/bin/bash

source="/home/.nuts/squashfs/"
target="/"

rsync \
    -aHAXr \
    --exclude /proc/ \
    --exclude /sys/ \
    --exclude /dev/ \
    --exclude /run/ \
    --exclude /run/udev/ \
    --exclude /sys/firmware/efi/efivars/ \
    --exclude /etc/ \
    --exclude /home/ \
    --exclude /media/ \
    --exclude /mnt/ \
    --exclude /root/ \
    --exclude /srv/ \
    --exclude /tmp/ \
    --exclude /var/ \
    --progress \
    --inplace \
     "$source" "$target"
