#! /bin/sh


# -- Variables.

TITLE=ZNX-GUI-dev
STYLE=breeze


# -- Functions for the GUI.

ui="kdialog --title='$TITLE'"

_e () { $ui --error "$@"; }
notify () { $ui --passivepopup "$@" 5; }
ask () { $ui --yesno "$@"; }
as_root () { echo "$password" | sudo -Sk $@; }


# -- Determine znx binary.

ZNX_BIN=znx

select_command () {
	$ui --combobox "Command to run:" \
		init \
		fix-esp \
		deploy \
		rename \
		update \
		check-update \
		rollback \
		reset \
		clean \
		remove \
		status
}

select_device () { $ui --menu "Select device:" $(lsblk -npdlo NAME,LABEL,MODEL); }
select_image () { $ui --combobox "Select image:" $(as_root $ZNX_BIN list $1); }

get_source () { $ui --inputbox "URL, directory or file to deploy:"; }
get_image () { $ui --inputbox "Image name:"; }


# -- Wrappers for znx's commands.

_init () { as_root $ZNX_BIN -y init $1; }
_fix-esp () { as_root $ZNX_BIN fix-esp $1; }
_deploy () { as_root $ZNX_BIN deploy $1 $(get_image) "$(get_source)"; }
_rename () { as_root $ZNX_BIN rename $1 $(select_image $1) $(get_image); }
_update () { as_root $ZNX_BIN update $1 $(select_image $1); }
_check-update () { as_root $ZNX_BIN check-update $1 $(select_image $1); }
_rollback () { as_root $ZNX_BIN rollback $1 $(select_image $1); }
_reset () { as_root $ZNX_BIN -y reset $1 $(select_image $1); }
_clean () { as_root $ZNX_BIN -y clean $1 $(select_image $1); }
_remove () { as_root $ZNX_BIN -y remove $1 $(select_image $1); }

_status () {
	tmp=$(mktemp)
	as_root $ZNX_BIN status $1 $(select_image $1) > $tmp
	$ui --textbox $tmp
	rm -rf $tmp
}


#	Shortcut for enabling debugging.

[ "$1" = "-d" -o "$1" = "--debug" ] && {
	set -x
	shift
}


# -- Loop until the user closes the main window.

while :; do

	password=$($ui --password "To proceed, type your password.")

	cmd=$(select_command)

	[ ${#cmd} -gt 0 ] ||
		_e "Operation cancelled."

	_$cmd $(select_device) && {
		notify "Please wait. You will be notified when the command finishes." &
		$ui --msgbox "Operation completed successfully."
	} || {
		_e "Operation failed!"
	}

	ask "Do you want to perform another action?" ||
		exit

done
