# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: index
  version: 4.0.0+p22.04+vstable+git20241108.0240-0
  binarypath: /usr/bin/index
  distrorepo:
    - distro: ubuntu
      release: jammy
      arch: amd64
      components:
          - main
          - universe
    - distro: kde-neon
      release: jammy
      arch: amd64
  deps:
    - index
    - kf6-breeze-icon-theme
    - kf6-karchive
    - kf6-kauth
    - kf6-kbookmarks
    - kf6-kcodecs
    - kf6-kcolorscheme
    - kf6-kcompletion
    - kf6-kconfig
    - kf6-kconfigwidgets
    - kf6-kcoreaddons
    - kf6-kcrash
    - kf6-kdbusaddons
    - kf6-kfilemetadata
    - kf6-kguiaddons
    - kf6-ki18n
    - kf6-kiconthemes
    - kf6-kio
    - kf6-kirigami
    - kf6-kitemviews
    - kf6-kjobwidgets
    - kf6-knotifications
    - kf6-kservice
    - kf6-kstatusnotifieritem
    - kf6-kwidgetsaddons
    - kf6-kwindowsystem
    - kf6-solid
    - libasound2
    - libasyncns0
    - libb2-1
    - libcanberra0
    - libdouble-conversion3
    - libduktape207
    - libflac8
    - libgomp1
    - libicu70
    - libimobiledevice6
    - libltdl7
    - libmauikit
    - libmauikitaccounts4
    - libmauikitarchiver4
    - libmauikitfilebrowsing4
    - libmauikitimagetools4
    - libmauikitterminal4
    - libmauiman
    - libmd4c0
    - libogg0
    - libopus0
    - libpcre2-16-0
    - libplist3
    - libsndfile1
    - libtdb1
    - libusbmuxd6
    - libvorbis0a
    - libvorbisenc2
    - libvorbisfile3
    - libxcb-cursor0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-res0
    - libxcb-shape0
    - libxcb-xinput0
    - libxcb-xkb1
    - libxkbcommon0
    - mauiman
    - qml6-module-org-maui-mauikit
    - qml6-module-org-mauikit-accounts
    - qml6-module-org-mauikit-archiver
    - qml6-module-org-mauikit-filebrowsing
    - qml6-module-org-mauikit-imagetools
    - qml6-module-org-mauikit-terminal
    - qt6-5compat
    - qt6-base
    - qt6-declarative
    - qt6-gtk-platformtheme
    - qt6-multimedia
    - qt6-wayland
    - xkb-data
  runtime: go

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/index"
  envvars:
    QT_QPA_PLATFORM: "xcb"
    QT_PLUGIN_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/plugins:$APPDIR/usr/lib/x86_64-linux-gnu/qt6/plugins"
    QT_QML_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/qml:$APPDIR/usr/lib/x86_64-linux-gnu/qt6/qml"
    QML_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt6/qml"
    QML2_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/qml"
    SESSION_MANAGER: ""
    XKB_CONFIG_ROOT: "$APPDIR/usr/share/X11/xkb"
  prebuild_commands:
    - "rm -f $APPDIR/usr/share/metainfo/org.kde.index.appdata.xml"

sandbox:
  type: none

integration:
  type: gui
